version: '3.8'

services:
  api-backend:
    build: ../
    container_name: api-backend
    ports:
      - "10000:10000"
    volumes:
      - ../:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    external_links:
      - postgres
      - redis
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
  node_modules: